### ISSUE TITLE
Is the transcript.txt in data/test1 correct ?

### ISSUE THREAD

**Issue by Kimonode** [mozilla/DSAlign#1]
I ran ./bin/gettestdata.sh and the transcript.txt file downloaded in data/test1 does not contain the transcript of the wav file downloaded with it.

Instead, transcript.txt only contains Google legal disclaimer _"Google. This is a digital copy of a book that was preserved for generations on library shelves before it was carefully scanned by Google as part of a project [etc.]"_.

Did I miss something or did anything wrong ?

**Comment by tilmankamp** [comment]
Yes, this note from Google is part of the text and intentionally left in to validate the algorithm's ability to deal with such things. Just scroll up/down to see the actual content.
