### ISSUE TITLE
aligned output json doesn't have unicode text

### ISSUE THREAD

**Issue by tensorfoo** [mozilla/DSAlign#10]
Instead of showing unicode aligned text strings, it has for example strings that look like "\uXXXX\uYYYY....". Any way to tell the tool to output unicode correctly? 

edit. Something like `"".join(s)` is the desired output instead of the `s` in the output.

**Comment by tilmankamp** [comment]
One could add `ensure_ascii=False` to the `json.dump` calls.

**Comment by tensorfoo** [comment]
> One could add `ensure_ascii=False` to the `json.dump` calls.

That worked. Thank you. Should that have been the default behaviour?

**Comment by tilmankamp** [comment]
Covered by #32
