### ISSUE TITLE
MemoryError when calling align on a large audio file (~1gb mp3)

### ISSUE THREAD

**Issue by tensorfoo** [mozilla/DSAlign#11]
```
> Traceback (most recent call last):
>   File "DSAlign/align/align.py", line 653, in <module>
>     main()
>   File "DSAlign/align/align.py", line 593, in main
>     segments, rate, audio_length = wavSplit.vad_segment_generator(audio, aggressiveness)
>   File "DSAlign/align/wavSplit.py", line 122, in vad_segment_generator
>     audio = (AudioSegment.from_file(audio_file)
>   File "DSAlign/venv/lib/python3.6/site-packages/pydub/audio_segment.py", line 706, in from_file
>     p_out = bytearray(p_out)
> 
```

I was just curious to see how DSAlign would handle a large input. Perhaps instead of generating all the segments all at once and then processing them, we could generate and consume segments as needed. Not sure how that would work in practice or if it would be too complicated to make such a change. Also is it ok to make issues like these or am I being a nuisance?

**Comment by tensorfoo** [comment]
It seems this is an [issue with pydub](https://github.com/jiaaro/pydub/issues/135) but they seem uninterested in fixing it, so this limitation will remain indefinitely as long as we're using pydub.

**Comment by tensorfoo** [comment]
So a bit of investigation and i came across the[ pyav library](https://github.com/mikeboers/PyAV) as an alternative to pydub. It is fairly simply to load the mp3 into RAM using the following code: 
```
import av
c = av.open("largefile.mp3")
cd = c.decode(audio=0)
```
which yields a generator, 
`>>> cd
<generator object at 0x7fe3e5ac0af8>`

which we can use lazily like: 
`>>> f = next(cd)
<av.AudioFrame 0, pts=0, 576 samples at 22050Hz, mono, s16p at 0x7fe3e598c6c8>`


```
>>> R = av.audio.resampler.AudioResampler(rate=16000)
>>> f.pts = 0
>>> R.resample(f)
<av.AudioFrame 3, pts=None, 402 samples at 16000Hz, mono, s16p at 0x7fe3e598c660>

```

So wavsplit.py would have to be modified to use pyav like this but the benefit would be being able to lazily consume the audio file. It's already been written to use generators (yield etc) so this would be a better fit than pydub.

**Comment by tilmankamp** [comment]
Now [DeepSpeech](https://github.com/mozilla/DeepSpeech/) supports transcribing audio files to `.tlog` files through its `transcribe.py` [tool](https://github.com/mozilla/DeepSpeech/blob/master/transcribe.py). It is implemented in a way that should avoid keeping an audio file completely in memory.

```
$ python transcribe.py --batch_size 30 --src audio.wav --dst audio.tlog --checkpoint_dir ../checkpoint-0.6.0/
```
