### ISSUE TITLE
Use other STT systems ?

### ISSUE THREAD

**Issue by noe** [mozilla/DSAlign#13]
Are you planning to support other STT systems, like [Baidu's DeepSpeech 2](https://github.com/PaddlePaddle/DeepSpeech)? This would make it possible to use their [pretrained models](https://github.com/PaddlePaddle/DeepSpeech#released-models), which are said to be very good for Chinese.

**Comment by tilmankamp** [comment]
There are no such plans yet. For now you could use another STT system in combination with some script to produce `.tlog` files. This could be a viable option for an actual integration.
