### ISSUE TITLE
Fix for Mac OSX

### ISSUE THREAD

**Issue by BoneGoat** [mozilla/DSAlign#16]
I'm running this on a Mac. Please don't hate me. Readlink doesn't work on a Mac so I made some changes here: https://github.com/BoneGoat/DSAlign/commit/f62b23992e841e8dca7a56a7cb8fb5947f1d6eb5
It's not portable but if there is interest we can fix that.

**Comment by tilmankamp** [comment]
How about the following:
```
approot=`python -c 'import os, sys; print os.path.dirname(os.path.realpath(sys.argv[0]))'`
```
Should be platform independent. Could you test this on OSX? It also would have to be applied to the other scripts in `bin`.

**Comment by tilmankamp** [comment]
My last comment was wrong - hided it. This complete version of `bin/align.sh` should also work from other places:
```
#!/usr/bin/env bash
cd `python -c "import os, sys; print os.path.dirname(os.path.dirname(os.path.realpath(\"$0\")))"`
source venv/bin/activate
python align/align.py "$@"
stty sane
```

**Comment by tilmankamp** [comment]
Disadvantage of this solution is that it won't work, if somebody specifies relative paths for some argument while being outside the project root.

**Comment by tilmankamp** [comment]
Best would probably be to establish an APP_ROOT environment variable and read it in the Python files when things should be loaded from within the project tree (alphabet fallback, models etc.). I think I'll prepare a PR and put you on review.

**Comment by lunixbochs** [comment]
I usually use this pattern btw, saves a shell out to python:
```
base=$(cd "$(dirname "$0")" && pwd)
```
For double dirname you can either add a `/..` or another `"$(dirname "$(dirname "$0")")"`
```
base=$(cd "$(dirname "$0")"/.. && pwd)
```
