### ISSUE TITLE
where is buildkenlm.sh?

### ISSUE THREAD

**Issue by msubhash** [mozilla/DSAlign#2]
Did not find it in bin/buildkenlm.sh?

**Comment by tilmankamp** [comment]
This is a README issue: You should use `bin/lm-dependencies.sh` instead. Just fixed it.

**Comment by msubhash** [comment]
Thanks.. 
Can it do word level Forced alignment?  I want to extract timestamp of each word in audio..

**Comment by tilmankamp** [comment]
Unfortunately not (yet). DeepSpeech has support for that, but it's not integrated into alignment yet.

**Comment by msubhash** [comment]
Thanks for quick revert. Do you know any way to get the word level forced alignment done using deepspeech or any other tool?
