### ISSUE TITLE
inconsistencies

### ISSUE THREAD

**Issue by Tortoise17** [mozilla/DSAlign#25]
there are some inconsistencies in the new update. 
like 
in requirement, tqdm is removed while in align.py it is importing. 
also.
`/align.py", line 364, in progress
    return it if args.no_progress else log_progress(it, interval=args.progress_interval, total=total)
NameError: name 'log_progress' is not defined`

Also, a question. with this change, is there any improvement in the handling of fragment / transcript log ?

**Comment by tilmankamp** [comment]
Thanks for reporting this. I will also remove `tqdm` from `stats.py` now. These changes should not affect handling of fragment or transcript log.

**Comment by Tortoise17** [comment]
Welcome sir, my pleasure. 
I am thinking to make a word level splitting or any small possibilities of chunks other than time window. If you can assist anytime.

**Comment by argideritzalpea** [comment]
Hi @Tortoise17 and @tilmankamp
This project is awesome. Are there any near-term plans to make word-level and subword-level alignment a possibility? This would be insanely useful for phonological analysis if subword-level alignment were enabled and you could export .textgrid files to Praat with custom language models enabled by CommonVoice
