### ISSUE TITLE
INFO:root:Fragment 11: character error rate (CER) too high

### ISSUE THREAD

**Issue by Aradhya0510** [mozilla/DSAlign#3]
Running the test1 to check the alignment gives out high character error rate, possibly due to the current deepspeech model supplemented with the project. will there be an updated model available? I can provide trained weights for the tensorflow/deepspeech2 implementation if you wanna integrate that with the project.

**Comment by tilmankamp** [comment]
This depends on `--output-max-cer` setting. As soon as a new DeepSpeech release is out, I'll update its version in the download and installation scripts.
