### ISSUE TITLE
Dataset/catalog access

### ISSUE THREAD

**Issue by nicolaspanel** [mozilla/DSAlign#30]
Hi @tilmankamp and thank you for sharing this !
I assume you have used DSAlign to generate large datasets from sources like librivox.
Do you plan to share them with the community?
Best regards

**Comment by tilmankamp** [comment]
Yes, you are right. We already used this approach to align large data sets with many thousand hours. Our plan is to eventually share them with the community once they have been vetted for quality and by our legal team.
