### ISSUE TITLE
Tensorflow warning

### ISSUE THREAD

**Issue by ishan-modi** [mozilla/DSAlign#39]
When I am aligning my audio and transcript. It is getting aligned successfully but here is my log.

INFO:root:VAD splitting
        2 (elapsed: 00:00:00, speed: 358.30 it/s)
TensorFlow: v1.15.0-24-gceb46aa
DeepSpeech: v0.7.1-0-g2e9c281
INFO:root:Transcribing
**2020-12-02 11:15:00.031793: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA**
 1 of 2 :  50.00% (elapsed: 00:00:03, speed: 0.29 it/s, ETA: 00:00:03)
 2 of 2 : 100.00% (elapsed: 00:00:03, speed: 2.07 it/s, ETA: 00:00:00)
INFO:root:Aligning
 1 of 1 : 100.00% (elapsed: 00:00:00, speed: 5.17 it/s, ETA: 00:00:00)
INFO:root:Aligned 2 fragments

should I be concerned with the highlighted warning or it is fine. Why is this occuring

**Comment by Tortoise17** [comment]
This is working fine . Could be little slow due to maybe old cpu or tensorflow compilation

**Comment by ishan-modi** [comment]
Thank you for the response. Appreciate it !!!
