### ISSUE TITLE
word level alignment

### ISSUE THREAD

**Issue by Tortoise17** [mozilla/DSAlign#6]
Instead of fragments, is there any easy way to get the word by word (word level) alignment? Pleae guide and help.

**Comment by tilmankamp** [comment]
Unfortunately not (yet). I'll soon put up `transcribe.py` either as part of DeepSpeech or part of this project. It should be possible to extend it to word level alignments (added to `.tlog` files). From there it's a short path to also get word level alignments...

**Comment by abhisheknovoic** [comment]
Hello @tilmankamp , just curious to know if this piece of work is complete. Can you please update us on whether the word level alignment is now supported as part of DSAlign? Thanks for the great work anyways.

**Comment by Errorbot1122** [comment]
Please add word level alinement
