### ISSUE TITLE
trying to run the example in the readme.md 

### ISSUE THREAD

**Issue by tensorfoo** [mozilla/DSAlign#7]
```
$ bin/align.sh --output-max-cer 15 --loglevel 10 data/test1/audio.wav data/test1/transcript.txt data/test1/aligned.json

align.py: error: unrecognized arguments: data/test1/audio.wav data/test1/transcript.txt data/test1/aligned.json
```

it seems the app has been rewritten to require flags that are not present in the example. i've tried adding in --audio and --script but it's unclear what to put before the 3rd argument (the json one). Also is there a step missing somewhere that would have generated the json file?

**Comment by Tortoise17** [comment]
-- aligned
-- script
they are missing.

**Comment by tensorfoo** [comment]
thank you @Tortoise17, that worked, 

`bin/align.sh --output-max-cer 15 --loglevel 10 --audio data/test1/audio.wav --script data/test1/transcript.txt --aligned data/test1/aligned.json --tlog data/test1/log.txt`
