### ISSUE TITLE
Doesn't use GPU

### ISSUE THREAD

**Issue by bwang482** [mozilla/DSAlign#8]
I am testing DSAlign with the example data. Everything is installed and configured exactly as in the readme file. However, it doesn't seem to use GPUs. How do I make sure it does use GPUs please? Thanks!

**Comment by tensorfoo** [comment]
How are you checking if GPU is being used? I'm also very new to DSAlign but i've got it using GPU. Make sure you have set it up correctly to use deepspeech-gpu and install the native client from https://tools.taskcluster.net/index/project.deepspeech.deepspeech.native_client.master/gpu for the right python version (prob 3.6). 

eg,` pip install --upgrade https://index.taskcluster.net/v1/task/project.deepspeech.deepspeech.native_client.master.03e281864994d05f326420696d98d3367d0a55b0.gpu/artifacts/public/deepspeech_gpu-0.6.0a4-cp36-cp36m-manylinux1_x86_64.whl
`

**Comment by tilmankamp** [comment]
It will use the GPU, once you remove package `deepspeech` and install `deepspeech_gpu` instead.
